#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VideoMarket")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMusteriler(Musteriler instance);
    partial void UpdateMusteriler(Musteriler instance);
    partial void DeleteMusteriler(Musteriler instance);
    partial void InsertFilmSati(FilmSati instance);
    partial void UpdateFilmSati(FilmSati instance);
    partial void DeleteFilmSati(FilmSati instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::linqToSql.Properties.Settings.Default.VideoMarketConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Musteriler> Musterilers
		{
			get
			{
				return this.GetTable<Musteriler>();
			}
		}
		
		public System.Data.Linq.Table<FilmSati> FilmSatis
		{
			get
			{
				return this.GetTable<FilmSati>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteriler")]
	public partial class Musteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MusteriNo;
		
		private string _MusteriAd;
		
		private string _MusteriSoyad;
		
		private string _Telefon;
		
		private string _Adres;
		
		private bool _Silindi;
		
		private EntitySet<FilmSati> _FilmSatis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriNoChanging(int value);
    partial void OnMusteriNoChanged();
    partial void OnMusteriAdChanging(string value);
    partial void OnMusteriAdChanged();
    partial void OnMusteriSoyadChanging(string value);
    partial void OnMusteriSoyadChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public Musteriler()
		{
			this._FilmSatis = new EntitySet<FilmSati>(new Action<FilmSati>(this.attach_FilmSatis), new Action<FilmSati>(this.detach_FilmSatis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MusteriNo
		{
			get
			{
				return this._MusteriNo;
			}
			set
			{
				if ((this._MusteriNo != value))
				{
					this.OnMusteriNoChanging(value);
					this.SendPropertyChanging();
					this._MusteriNo = value;
					this.SendPropertyChanged("MusteriNo");
					this.OnMusteriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MusteriAd
		{
			get
			{
				return this._MusteriAd;
			}
			set
			{
				if ((this._MusteriAd != value))
				{
					this.OnMusteriAdChanging(value);
					this.SendPropertyChanging();
					this._MusteriAd = value;
					this.SendPropertyChanged("MusteriAd");
					this.OnMusteriAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriSoyad", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MusteriSoyad
		{
			get
			{
				return this._MusteriSoyad;
			}
			set
			{
				if ((this._MusteriSoyad != value))
				{
					this.OnMusteriSoyadChanging(value);
					this.SendPropertyChanging();
					this._MusteriSoyad = value;
					this.SendPropertyChanged("MusteriSoyad");
					this.OnMusteriSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(20)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(150)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_FilmSati", Storage="_FilmSatis", ThisKey="MusteriNo", OtherKey="MusteriNo")]
		public EntitySet<FilmSati> FilmSatis
		{
			get
			{
				return this._FilmSatis;
			}
			set
			{
				this._FilmSatis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FilmSatis(FilmSati entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = this;
		}
		
		private void detach_FilmSatis(FilmSati entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FilmSatis")]
	public partial class FilmSati : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatisNo;
		
		private System.DateTime _Tarih;
		
		private int _FilmNo;
		
		private int _MusteriNo;
		
		private int _Adet;
		
		private decimal _BirimFiyat;
		
		private bool _Silindi;
		
		private EntityRef<Musteriler> _Musteriler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatisNoChanging(int value);
    partial void OnSatisNoChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnFilmNoChanging(int value);
    partial void OnFilmNoChanged();
    partial void OnMusteriNoChanging(int value);
    partial void OnMusteriNoChanged();
    partial void OnAdetChanging(int value);
    partial void OnAdetChanged();
    partial void OnBirimFiyatChanging(decimal value);
    partial void OnBirimFiyatChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public FilmSati()
		{
			this._Musteriler = default(EntityRef<Musteriler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SatisNo
		{
			get
			{
				return this._SatisNo;
			}
			set
			{
				if ((this._SatisNo != value))
				{
					this.OnSatisNoChanging(value);
					this.SendPropertyChanging();
					this._SatisNo = value;
					this.SendPropertyChanged("SatisNo");
					this.OnSatisNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmNo", DbType="Int NOT NULL")]
		public int FilmNo
		{
			get
			{
				return this._FilmNo;
			}
			set
			{
				if ((this._FilmNo != value))
				{
					this.OnFilmNoChanging(value);
					this.SendPropertyChanging();
					this._FilmNo = value;
					this.SendPropertyChanged("FilmNo");
					this.OnFilmNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriNo", DbType="Int NOT NULL")]
		public int MusteriNo
		{
			get
			{
				return this._MusteriNo;
			}
			set
			{
				if ((this._MusteriNo != value))
				{
					if (this._Musteriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriNoChanging(value);
					this.SendPropertyChanging();
					this._MusteriNo = value;
					this.SendPropertyChanged("MusteriNo");
					this.OnMusteriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int NOT NULL")]
		public int Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirimFiyat", DbType="Money NOT NULL")]
		public decimal BirimFiyat
		{
			get
			{
				return this._BirimFiyat;
			}
			set
			{
				if ((this._BirimFiyat != value))
				{
					this.OnBirimFiyatChanging(value);
					this.SendPropertyChanging();
					this._BirimFiyat = value;
					this.SendPropertyChanged("BirimFiyat");
					this.OnBirimFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_FilmSati", Storage="_Musteriler", ThisKey="MusteriNo", OtherKey="MusteriNo", IsForeignKey=true)]
		public Musteriler Musteriler
		{
			get
			{
				return this._Musteriler.Entity;
			}
			set
			{
				Musteriler previousValue = this._Musteriler.Entity;
				if (((previousValue != value) 
							|| (this._Musteriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Musteriler.Entity = null;
						previousValue.FilmSatis.Remove(this);
					}
					this._Musteriler.Entity = value;
					if ((value != null))
					{
						value.FilmSatis.Add(this);
						this._MusteriNo = value.MusteriNo;
					}
					else
					{
						this._MusteriNo = default(int);
					}
					this.SendPropertyChanged("Musteriler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
